language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-pushover.gemspec
- gem install sensu-plugins-pushover-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: etsEO1mszocoQGVZs6r8SfIMb25yetC7sOLwpKVUArHSSxxU4Cx3+27BsAeVj1EdQ+86Txvwr8CVnwaOLxQN65W1wNXZ6jIefyq8wpPpXrCvPFeKiLrOQ8j9PcCaOsTwJ6gErojsNErhWS6clVaRlVCJh8lhrDrQSR8eY56MjkU=
  gem: sensu-plugins-pushover
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-pushover
